### ISSUE TITLE
TODO list for wp-e2e-bridge

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#60]
I've created a new project to bridge the wp-calypso repo with wp-e2e-tests, to be able to run the e2e tests against a specific branch in a PR.  I have proof of concept code working, but here's what remains:
- [ ] Create new label in wp-calypso for "Run e2e Tests"
- [x] Add capability wp-e2e-bridge to remove the above label when tests are initiated
- [ ] Create wp-e2e-bridge repo under Automattic
- [ ] Find generic Git and CircleCI tokens to use, and a secure place to store/access them
- [ ] Find best place to run wp-e2e-bridge (currently on free OpenShift container)
- [ ] Add webhook to wp-calypso for PR updates
- [ ] Update CircleCI webhook (on wp-e2e-tests) to point to production wp-e2e-bridge
- [x] Update wp-e2e-tests to look for `liveBranches` build_parameter and use that to populate `calypsoBaseURL`

**Comment by hoverduck** [comment]
Closing with the plan to move to an alternate implementation with Docker containers
